In [1]:
#part 1 - Data Preprocessing
#We_are_trying_to_predict_which_of_the_customers_will_leave_the_bank_by_learning_from_the_data_set
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset=pd.read_csv('Churn_Modelling.csv')

In [2]:
print(dataset)

      RowNumber  CustomerId         Surname  CreditScore Geography  Gender  \
0             1    15634602        Hargrave          619    France  Female   
1             2    15647311            Hill          608     Spain  Female   
2             3    15619304            Onio          502    France  Female   
3             4    15701354            Boni          699    France  Female   
4             5    15737888        Mitchell          850     Spain  Female   
5             6    15574012             Chu          645     Spain    Male   
6             7    15592531        Bartlett          822    France    Male   
7             8    15656148          Obinna          376   Germany  Female   
8             9    15792365              He          501    France    Male   
9            10    15592389              H?          684    France    Male   
10           11    15767821          Bearce          528    France    Male   
11           12    15737173         Andrews          497     Spa

In [86]:
X=dataset.iloc[:,3:13].values
y=dataset.iloc[:,13].values
print(X[0])

[619 'France' 'Female' 42 2 0.0 1 1 1 101348.88]


In [87]:
#Encoding categorical data
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder_1=LabelEncoder()
X[ : , 1] = labelencoder_1.fit_transform(X[ : , 1])
labelencoder_2=LabelEncoder()
X[ : , 2] = labelencoder_2.fit_transform(X[ : , 2])
#creating dummy variable for countries(cuz france is not higher than germany)
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()

C:\Users\user\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\user\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [88]:
#to avoid multicolinearity i.e. dummy variable trap(i.e. using m-1 variables for representing m dummy variable)
X=X[:,1:]

0.0 0.0 619.0 0.0 42.0 2.0 0.0 1.0 1.0 1.0 101348.88 

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [7]:
#applying feature scaling
from sklearn.preprocessing import StandardScaler
X_train = StandardScaler().fit_transform(X_train)
X_test = StandardScaler().fit_transform(X_test)

In [8]:
#lets make the ann
#the sequential module is required to intialize the neural network
#the dense module is required to build the layers of our ANN
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [9]:
#initialising the ANN 
classifier = Sequential()

In [10]:
#Adding the input layer and first hidden layer
classifier.add(Dense(units=6, kernel_initializer='uniform', activation='relu', input_dim=11)) #here output_dim is no of hidden layer you want to add so we'll add (inp+out)/2

In [11]:

#Adding the second hidden layer
classifier.add(Dense(units=6, kernel_initializer='uniform', activation='relu')) #note: kernel_initializer='uniform' initializes the weights to small random no. close to zero

In [12]:

#Adding the output layer 
classifier.add(Dense(units=1, kernel_initializer='uniform', activation='sigmoid'))

In [13]:
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])#here adam optimizer is schoastic gradient descent algo and if our dependent variabale has binary outcome then the logarathmic loss function is called binary_crossentropy and if the dependent variable has more than two categories then it is called 'categorical_crossentropy' and the metrics is for evaluating our performance after each epoch

In [14]:
#fitting the Ann to the training set
classifier.fit(X_train, y_train,batch_size=10,epochs=100)

Epoch 1/100
8000/8000 [==============================] - 4s 456us/step - loss: 0.4868 - acc: 0.7957
Epoch 2/100
8000/8000 [==============================] - 2s 195us/step - loss: 0.4295 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 165us/step - loss: 0.4261 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 130us/step - loss: 0.4222 - acc: 0.8102
Epoch 5/100
8000/8000 [==============================] - 1s 129us/step - loss: 0.4196 - acc: 0.8202 0s - loss: 0
Epoch 6/100
8000/8000 [==============================] - 1s 127us/step - loss: 0.4171 - acc: 0.8237
Epoch 7/100
8000/8000 [==============================] - 2s 197us/step - loss: 0.4153 - acc: 0.8262
Epoch 8/100
8000/8000 [==============================] - 2s 213us/step - loss: 0.4138 - acc: 0.8291
Epoch 9/100
8000/8000 [==============================] - 1s 152us/step - loss: 0.4125 - acc: 0.8299
Epoch 10/100
8000/8000 [==============================] - 1s 170us/step - loss: 0.4112 

8000/8000 [==============================] - 1s 139us/step - loss: 0.3944 - acc: 0.8360
Epoch 83/100
8000/8000 [==============================] - 1s 139us/step - loss: 0.3943 - acc: 0.8371
Epoch 84/100
8000/8000 [==============================] - 1s 146us/step - loss: 0.3936 - acc: 0.8371
Epoch 85/100
8000/8000 [==============================] - 1s 156us/step - loss: 0.3940 - acc: 0.8371
Epoch 86/100
8000/8000 [==============================] - 1s 170us/step - loss: 0.3938 - acc: 0.8376
Epoch 87/100
8000/8000 [==============================] - 2s 211us/step - loss: 0.3943 - acc: 0.8356
Epoch 88/100
8000/8000 [==============================] - 1s 141us/step - loss: 0.3942 - acc: 0.8371
Epoch 89/100
8000/8000 [==============================] - 1s 139us/step - loss: 0.3938 - acc: 0.8364
Epoch 90/100
8000/8000 [==============================] - 1s 167us/step - loss: 0.3940 - acc: 0.8370
Epoch 91/100
8000/8000 [==============================] - 1s 134us/step - loss: 0.3939 - acc: 0.8354
Epo

In [29]:
#predicting the Test set results
print(X_test[0])
y_pred=classifier.predict(X_test)

[ 1.62776996 -0.57427105 -0.56129438 -1.11339196 -0.39401698  0.9869706
  0.85962168 -0.8733766   0.66011376  0.97628121  1.62185911]


In [19]:
print(y_pred)

[[0.19719225]
 [0.3298049 ]
 [0.14546517]
 ...
 [0.20677757]
 [0.11227079]
 [0.13014305]]


In [20]:
#converting y_pred into True and False based on 50% threshold in order to compute cm
y_pred =(y_pred>0.5)

In [21]:
print(y_pred)

[[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [False]]


In [22]:
#Making the confusion matrix
from sklearn.metrics import confusion_matrix 
cm=confusion_matrix(y_test, y_pred)

In [23]:
print(cm)

[[1554   41]
 [ 262  143]]


In [25]:
#calculating accuracy of model
print((1554+143)/2000)

0.8485


In [27]:
#predicting a single new observation
# Using our ANN model to predict if the customer with the following informations will leave the bank: 

# Geography: France
# Credit Score: 600
# Gender: Male
# Age: 40 years old
# Tenure: 3 years
# Balance: $60000
# Number of Products: 2
# Does this customer have a credit card ? Yes
# Is this customer an Active Member: Yes
# Estimated Salary: $50000
# So should we say goodbye to that customer ?

In [89]:
X_sample = np.array([0 , 0, 600, 1, 40,  3, 60000, 2,  1,  1, 50000])
X_sample = X_sample.reshape(-1,1)
print(X_sample)

[[    0]
 [    0]
 [  600]
 [    1]
 [   40]
 [    3]
 [60000]
 [    2]
 [    1]
 [    1]
 [50000]]


In [90]:
X_sample = StandardScaler().fit_transform(X_sample)

In [91]:
X_sample = X_sample.reshape(1,-1)
print(X_sample)

[[-0.472 -0.472 -0.444 -0.472 -0.471 -0.472  2.345 -0.472 -0.472 -0.472
   1.876]]


In [92]:
y_pred_sample=classifier.predict(X_sample)

In [93]:
y_pred_sample =(y_pred_sample>0.5)

In [95]:
print(y_pred_sample)

[[False]]


In [ ]:
#hence the customer with following info stays in the bank